# Exported from Render
version: "1"
services:
  - type: web
    name: n8n
    runtime: image
    image:
      url: docker.n8n.io/n8nio/n8n:latest
    plan: free
    region: oregon
    autoDeploy: true
    envVars:
      - key: DB_TYPE
        value: mysqldb
      - key: DB_MYSQLDB_HOST
        value: "148.113.47.114"
      - key: DB_MYSQLDB_PORT
        value: "3306"
      - key: DB_MYSQLDB_DATABASE
        value: "npczxzbp_n8n"
      - key: DB_MYSQLDB_USER
        value: "ektool"
      - key: DB_MYSQLDB_PASSWORD
        value: "ekTool@123"
      # Optional: set to your external URL so webhooks work
      #- key: WEBHOOK_URL
      #  value: https://your-n8n.onrender.com
